openapi: "3.0.1"
info:
  title: "gratitude-trial1"
  version: "1.0"
servers:
- url: "https://9lfgxk6c41.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/Prod"
paths:
  /category/user/{username}:
    get:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
  /user/{username}/category/{category}:
    post:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
    delete:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
  /compliment/{category}:
    get:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
  /user/{username}:
    get:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
  /compliment/user/{username}:
    get:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
components: {}
