openapi: "3.0.1"
info:
  title: "gratitude-trial1"
  version: "1.0"
servers:
- url: "https://9lfgxk6c41.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/Prod"
paths:
  /category/user/{username}:
    get:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "arn:aws:iam::773951294391:role/gratitude-trial1-getCategoriesForUserWorkflowgetCa-WVD0E23RD3EV"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:states:action/StartExecution"
        responses:
          "200":
            statusCode: "200"
          "400":
            statusCode: "400"
        requestTemplates:
          application/json: "{\"input\": \"$util.escapeJavaScript($input.json('$'))\"\
            , \"stateMachineArn\": \"arn:aws:states:us-east-1:773951294391:stateMachine:getCategoriesForUserWorkflow-cp1Y13aGOz2M\"\
            }"
        passthroughBehavior: "when_no_match"
  /user/{username}/category/{category}:
    post:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "arn:aws:iam::773951294391:role/gratitude-trial1-postUserCategoryWorkflowpostUserC-1DRB3VMV6VGRV"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:states:action/StartExecution"
        responses:
          "200":
            statusCode: "200"
          "400":
            statusCode: "400"
        requestTemplates:
          application/json: "{\"input\": \"$util.escapeJavaScript($input.json('$'))\"\
            , \"stateMachineArn\": \"arn:aws:states:us-east-1:773951294391:stateMachine:postUserCategoryWorkflow-0H1S8bMwbhW8\"\
            }"
        passthroughBehavior: "when_no_match"
    delete:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "arn:aws:iam::773951294391:role/gratitude-trial1-deleteUserCategoryWorkflowdeleteU-1RB3N8LFX6OYP"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:states:action/StartExecution"
        responses:
          "200":
            statusCode: "200"
          "400":
            statusCode: "400"
        requestTemplates:
          application/json: "{\"input\": \"$util.escapeJavaScript($input.json('$'))\"\
            , \"stateMachineArn\": \"arn:aws:states:us-east-1:773951294391:stateMachine:deleteUserCategoryWorkflow-BEfr4uUcj4uk\"\
            }"
        passthroughBehavior: "when_no_match"
  /compliment/{category}:
    get:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "arn:aws:iam::773951294391:role/gratitude-trial1-getComplimentByCategoryWorkflowge-ECOKHCUGRDRP"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:states:action/StartExecution"
        responses:
          "200":
            statusCode: "200"
          "400":
            statusCode: "400"
        requestTemplates:
          application/json: "{\"input\": \"$util.escapeJavaScript($input.json('$'))\"\
            , \"stateMachineArn\": \"arn:aws:states:us-east-1:773951294391:stateMachine:getComplimentByCategoryWorkflow-qpbmVwyuP7R1\"\
            }"
        passthroughBehavior: "when_no_match"
  /user/{username}:
    get:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "arn:aws:iam::773951294391:role/gratitude-trial1-getUserWorkflowgetUserInfoEventRo-1QQL3TFTIPP5M"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:states:action/StartExecution"
        responses:
          "200":
            statusCode: "200"
          "400":
            statusCode: "400"
        requestTemplates:
          application/json: "{\"input\": \"$util.escapeJavaScript($input.json('$'))\"\
            , \"stateMachineArn\": \"arn:aws:states:us-east-1:773951294391:stateMachine:getUserWorkflow-Qhb3dRcgP0FV\"\
            }"
        passthroughBehavior: "when_no_match"
  /compliment/user/{username}:
    get:
      responses:
        "400":
          description: "Bad Request"
          content: {}
        "200":
          description: "OK"
          content: {}
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: "arn:aws:iam::773951294391:role/gratitude-trial1-getComplimentByUsernameWorkflowge-1TY87VWQF7MW"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:states:action/StartExecution"
        responses:
          "200":
            statusCode: "200"
          "400":
            statusCode: "400"
        requestTemplates:
          application/json: "{\"input\": \"$util.escapeJavaScript($input.json('$'))\"\
            , \"stateMachineArn\": \"arn:aws:states:us-east-1:773951294391:stateMachine:getComplimentByUsernameWorkflow-BTtsEC69PWzd\"\
            }"
        passthroughBehavior: "when_no_match"
components: {}
x-amazon-apigateway-documentation:
  version: "3.0"
  createdDate: "2021-07-03T04:26:32Z"
  documentationParts:
  - location:
      type: "RESPONSE"
      path: "/category/user/{username}"
      method: "GET"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/category/user/{username}"
      method: "GET"
      statusCode: "400"
    properties:
      description: "Bad Request"
  - location:
      type: "RESPONSE"
      path: "/compliment/user/{username}"
      method: "GET"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/compliment/user/{username}"
      method: "GET"
      statusCode: "400"
    properties:
      description: "Bad Request"
  - location:
      type: "RESPONSE"
      path: "/compliment/{category}"
      method: "GET"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/compliment/{category}"
      method: "GET"
      statusCode: "400"
    properties:
      description: "Bad Request"
  - location:
      type: "RESPONSE"
      path: "/user/{username}/category/{category}"
      method: "DELETE"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/user/{username}/category/{category}"
      method: "DELETE"
      statusCode: "400"
    properties:
      description: "Bad Request"
  - location:
      type: "RESPONSE"
      path: "/user/{username}/category/{category}"
      method: "POST"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/user/{username}/category/{category}"
      method: "POST"
      statusCode: "400"
    properties:
      description: "Bad Request"
  - location:
      type: "RESPONSE"
      path: "/user/{username}"
      method: "GET"
      statusCode: "200"
    properties:
      description: "OK"
  - location:
      type: "RESPONSE"
      path: "/user/{username}"
      method: "GET"
      statusCode: "400"
    properties:
      description: "Bad Request"
