AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  ENV:
    Type: String
    Description: The environment staging name
    Default: env
  DevPhoneNumber:
    Type: String
    Description: The phone number to use for testing sms

Resources:
# BEGIN: Authentication
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_phone_number
            Priority: 1
      AutoVerifiedAttributes:
        - phone_number
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: gender
          AttributeDataType: String
          Mutable: true
          DeveloperOnlyAttribute: false
          Required: false
        - Name: race
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: birthdate
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: given_name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false 
        - Name: locale
          AttributeDataType: String
          Required: false
          Mutable: true     
      LambdaConfig:
        PostConfirmation: 
           Fn::ImportValue: !Sub "gratitude:${AWS::Region}:${ENV}:cognitoInsertTrigger:Arn"
      SmsConfiguration:
        SnsCallerArn: !GetAtt SmsRole.Arn #verify this is correct
        
  SnsSmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      ContentBasedDuplication: true
      DisplayName: 'Phone Number Verifier'
      FifoTopic: false

  SnsSmsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sms
      TopicArn: !GetAtt SnsSmsTopic.Arn

  SmsRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Iam role to call sns for sms messages
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cognito-idp.amazonaws.com
            Action:
              - sts:assumerole
      Policies:
        - PolicyName: sms-caller
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - sns:publish
                Resource:
                  - !GetAtt UserPool.Arn
  # END: Authentication
