version = 0.1
[init]
[init.deploy]
[init.deploy.parameters]
stack_name = "intial-version"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ot87qyuaqh7w"
s3_prefix = "intial-version"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
