AWSTemplateFormatVersion: 2010-09-09
Description: Complete Backend for Compliment API
Transform:
- AWS::Serverless-2016-10-31

# Globals:
#   Function:
#     Runtime: nodejs14.x
#     Environment:
#       Variables:
#           # "PGUSER": !Sub '{{resolve:secretsmanager:${secretDBAppInfo}::username}}'
#           # "PGHOST": !Sub '{{resolve:secretsmanager:${secretDBEndpoint}::address}}'
#           # "PGPASSWORD": !Sub '{{resolve:secretsmanager:${secretDBAppInfo}::password}}'
#           # "PGDATABASE": !Sub '{{resolve:secretsmanager:${secretDBAppInfo}::database}}'
#           # "PGPORT": !Sub '{{resolve:secretsmanager:${secretDBEndpoint}::port}}'
#           "PGUSER": "app_user"
#           "PGHOST": !GetAtt complimentRDS.Endpoint.Address
#           "PGPORT": !GetAtt complimentRDS.Endpoint.Address
#           "PGPASSWORD": "password"
#           "PGDATABASE": "compliments"
#     VpcConfig:
#         SecurityGroupIds:
#           - !Ref publicGroup
#         SubnetIds:
#           - !Ref sub1
# Metadata:

Parameters:
  ENV:
    Default: dev
    Description: The stage name of the environment
    Type: String

Mappings:
  AvailabilityZones:
    us-east-1:
      a: us-east-1a
      b: us-east-1b
      c: us-east-1c
Resources:
  NetworkingStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    Properties:
      Location: Networking.yml
      Parameters:
        ENV: !Ref ENV

  SecurityStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    Properties:
      Location: Security.yml
      Parameters:
        VPCId: !GetAtt NetworkingStack.Outputs.VPCId
        ENV: !Ref ENV

  PersistenceStack:
    Type: AWS::Serverless::Application
    DependsOn: SecurityStack
    DeletionPolicy: Delete
    Properties:
      Location: Persistence.yml
      Parameters:
        ENV: !Ref ENV
        az: !FindInMap [ AvailabilityZones, !Ref AWS::Region, 'a' ]

  FunctionStack:
    Type: AWS::Serverless::Application
    DependsOn: PersistenceStack
    DeletionPolicy: Delete
    Properties:
      Location: Functions.yml
      Parameters:
        ENV: !Ref ENV

  IntegrationsStack:
    Type: AWS::Serverless::Application
    DependsOn: AuthStack
    DeletionPolicy: Delete
    Properties:
      Location: Integrations.yml
      Parameters:
        ENV: !Ref ENV

  AuthStack:
    Type: AWS::Serverless::Application
    DependsOn: FunctionStack
    DeletionPolicy: Delete
    Properties:
      Location: Auth.yml
      Parameters:
        ENV: !Ref ENV

  DebugStack:
    Type: AWS::Serverless::Application
    DependsOn: SecurityStack
    DeletionPolicy: Delete
    
    Properties:
      Location: Debug.yml
      Parameters:
        ENV: !Ref ENV

  
Outputs:
  RDSEndpoint:
    Description: endpoint to connect to rds from lamdba, for debugging purposes
    Value: !GetAtt PersistenceStack.Outputs.complimentRDSAddress
  bastionIp:
    Description: The ip address of the ec2 instance
    Value: !GetAtt DebugStack.Outputs.bastionAddress
  restApiEndpoint:
    Description: endpoint to reach api gw
    Value: !GetAtt IntegrationsStack.Outputs.restApiUrl